#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
pass=0; fail=0
check(){ if eval "$2"; then printf 'PASS: %s\n' "$1"; pass=$((pass+1)); else printf 'FAIL: %s\n' "$1"; fail=$((fail+1)); fi; }
check "Build 0.9 branding" "grep -q 'Build 0.9' '$ROOT/src/appbranding.h'"
check "Dedicated Termux entry point" "test -f '$ROOT/src/main_termux.cpp' && test ! -f '$ROOT/src/main.cpp'"
check "Qt Core/Network only" "grep -q 'COMPONENTS Core Network' '$ROOT/CMakeLists.txt'"
check "No Qt Widgets" "! grep -Rqs 'Qt6::Widgets' '$ROOT/CMakeLists.txt' '$ROOT/src'"
check "No Qt Gui" "! grep -Rqs 'Qt6::Gui' '$ROOT/CMakeLists.txt' '$ROOT/src'"
check "No QApplication" "! grep -Rqs 'QApplication' '$ROOT/src'"
check "No XKB dependency" "! grep -q 'xkbcommon' '$ROOT/CMakeLists.txt'"
check "No desktop GUI source files" "test ! -e '$ROOT/src/mainwindow.cpp' && test ! -e '$ROOT/src/softphonewindow.cpp' && test ! -e '$ROOT/src/mediawindow.cpp'"
check "No CPAN command" "! grep -En '(^|[;&|[:space:]])cpan([[:space:]]|$)' '$ROOT/build-termux.sh'"
check "No Perl command" "! grep -En '(^|[;&|[:space:]])perl([[:space:]]|$)' '$ROOT/build-termux.sh'"
check "Termux pkg package manager" "grep -q 'pkg install' '$ROOT/build-termux.sh'"
check "No apt-get" "! grep -q 'apt-get' '$ROOT/build-termux.sh'"
check "Metadata-only xdg provider" "grep -q 'Contains no files' '$ROOT/build-termux.sh'"
check "Existing xdg-open reuse" "grep -q 'command -v xdg-open' '$ROOT/build-termux.sh' && grep -q 'termux-tools' '$ROOT/build-termux.sh'"
check "Explicit control permissions" "grep -q 'install -d -m 0755.*DEBIAN' '$ROOT/build-termux.sh' && grep -q 'chmod 0644.*control' '$ROOT/build-termux.sh'"
check "libopus package name" "grep -q 'libopus' '$ROOT/build-termux.sh'"
check "PJSIP 2.17 managed build" "grep -q 'branch 2.17' '$ROOT/build-termux.sh' && grep -q 'libpjproject' '$ROOT/CMakeLists.txt'"
check "PJSIP WaffleHouse account/call limits" "grep -q '#define PJSUA_MAX_ACC 32' '$ROOT/build-termux.sh' && grep -q '#define PJSUA_MAX_CALLS 64' '$ROOT/build-termux.sh' && grep -q '#define PJ_IOQUEUE_MAX_HANDLES 256' '$ROOT/build-termux.sh'"
check "PJSIP cached-limit validation" "grep -q 'pjsip_limits_ok' '$ROOT/build-termux.sh' && grep -q 'stale/default limits; rebuilding automatically' '$ROOT/build-termux.sh'"
check "PortAudio SIP backend" "grep -q -- '--with-external-pa' '$ROOT/build-termux.sh'"
check "Termux SIP JNI audio disabled" "grep -q '#define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 0' '$ROOT/build-termux.sh' && grep -q '#define PJMEDIA_AUDIO_DEV_HAS_OBOE 0' '$ROOT/build-termux.sh'"
check "Termux SIP cached JNI validation" "grep -q 'PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI.*0' '$ROOT/build-termux.sh'"
check "Termux native GUID backend" "grep -q 'guid_android.o' '$ROOT/build-termux.sh' && grep -q 'guid_simple.o' '$ROOT/build-termux.sh' && grep -q 'PJSIP Termux GUID configuration failed' '$ROOT/build-termux.sh'"
check "Termux cached GUID backend validation" "grep -q 'wafflehouse-termux-guid-backend' '$ROOT/build-termux.sh' && grep -q 'grep -qx.*guid_simple' '$ROOT/build-termux.sh'"
check "Runtime SIP GUID sanity gate" "grep -q 'verifyPjGuidBackend' '$ROOT/src/sipcore/SipEngine.cpp' && grep -q 'refusing to send malformed SIP transactions' '$ROOT/src/sipcore/SipEngine.cpp'"
check "Termux runtime uses TMPDIR" "grep -q 'absoluteEnvPath(\"TMPDIR\")' '$ROOT/src/sipcore/RuntimePaths.cpp' && grep -q 'absoluteEnvPath(\"PREFIX\")' '$ROOT/src/sipcore/RuntimePaths.cpp'"
check "Termux builder avoids literal /tmp scratch file" "grep -q 'TMPBASE=\"\${TMPDIR:-\$PREFIX_EXPECTED/tmp}\"' '$ROOT/build-termux.sh' && ! grep -Eq '/tmp/wh-xdg-status' '$ROOT/build-termux.sh'"
check "SIP startup error retained" "grep -q 'm_initializationError' '$ROOT/src/sipcontroller.cpp' && grep -q 'initializationError() const' '$ROOT/src/sipcontroller.h'"
check "SIP startup error visible in TUI" "grep -q '\\[error\\] SIP engine startup failed:' '$ROOT/src/terminalui.cpp'"
check "SIP saved passwords survive timeouts" "grep -q 'explicitAuthenticationFailure && !entry->settings.savePassword' '$ROOT/src/terminalui.cpp' && grep -q 'A transport/network failure is not evidence that the stored secret is' '$ROOT/src/terminalui.cpp'"
check "SIP timed-out disconnect is idempotent" "grep -q 'e.status == PJ_EINVALIDOP' '$ROOT/src/sipcontroller.cpp' && grep -q 'SIP account already offline' '$ROOT/src/sipcontroller.cpp'"
check "AIM/OSCAR retained" "test -f '$ROOT/src/oscarbackend.cpp' && grep -q 'oscarbackend.cpp' '$ROOT/CMakeLists.txt'"
check "IRC retained" "test -f '$ROOT/src/ircbackend.cpp' && grep -q 'ircbackend.cpp' '$ROOT/CMakeLists.txt'"
check "IRC slash commands retained" "grep -q '/nick' '$ROOT/src/terminalui.cpp'"
check "Telnet/BBS retained" "test -f '$ROOT/src/telnetbackend.cpp' && test -f '$ROOT/src/bbsdirectory.cpp'"
check "ANSI BBS terminal retained" "test -f '$ROOT/src/ansiterminal.cpp' && grep -q 'AnsiTerminalModel' '$ROOT/src/terminalui.cpp'"
check "SIP softphone retained" "test -f '$ROOT/src/sipbackend.cpp' && test -f '$ROOT/src/sipcore/SipEngine.cpp'"
check "SIP controls retained" "grep -q '/audio-devices' '$ROOT/src/terminalui.cpp' && grep -q '/hangup' '$ROOT/src/terminalui.cpp'"
check "Secure rooms retained" "test -f '$ROOT/src/secureroom.cpp' && grep -q 'secureroom.cpp' '$ROOT/CMakeLists.txt'"
check "Encrypted transfer retained" "test -f '$ROOT/src/filetransfer.cpp' && test -f '$ROOT/src/directtransfer.cpp' && test -f '$ROOT/src/securechannel.cpp'"
check "Media/streams retained" "test -f '$ROOT/src/mediacontroller.cpp' && grep -q '/mstream' '$ROOT/src/terminalui.cpp'"
check "CLI themes retained" "grep -q 'neon-miami' '$ROOT/src/terminalui.cpp' && grep -q 'waffle-iron' '$ROOT/src/terminalui.cpp'"
check "Termux shared Downloads support" "grep -q 'storage/downloads' '$ROOT/src/terminalui.cpp'"
check "Android notification audio" "grep -q 'termux-media-player' '$ROOT/src/notificationmanager.cpp'"
check "Android browser handoff" "grep -q 'termux-open-url' '$ROOT/src/terminalui.cpp'"
check "Termux SIP/RTP decoupled from audio hardware" "grep -q 'Termux deferred-hardware mode armed' '$ROOT/src/sipcore/SipEngine.cpp' && grep -q 'audio.setNullDev()' '$ROOT/src/sipcore/SipEngine.cpp'"
check "Termux media owns RTP ioqueue" "grep -q 'ec.medConfig.hasIoqueue=true' '$ROOT/src/sipcore/SipEngine.cpp' && grep -q 'ec.medConfig.threadCnt=1' '$ROOT/src/sipcore/SipEngine.cpp'"
check "Termux audio full-duplex fallback" "grep -q 'trying speaker-only' '$ROOT/src/sipcore/CallSession.cpp' && grep -q 'PJSUA_SND_DEV_SPEAKER_ONLY' '$ROOT/src/sipcore/CallSession.cpp'"
check "Capture failure preserves active call" "grep -q 'call remains active' '$ROOT/src/sipcore/CallSession.cpp'"
check "RTP telemetry retained" "grep -q 'localRtpAddress' '$ROOT/src/sipcore/CallSession.cpp' && grep -q 'getStreamStat' '$ROOT/src/sipcore/CallSession.cpp' && grep -q 'getMedTransportInfo' '$ROOT/src/sipcore/CallSession.cpp'"
check "Android microphone permission preflight installed" "test -x '$ROOT/scripts/termux-audio-preflight.sh' && grep -q 'wafflehouse-audio-preflight' '$ROOT/CMakeLists.txt' && grep -q 'termux-microphone-record' '$ROOT/scripts/termux-audio-preflight.sh'"
check "Global SIP registration trace" "grep -q 'recentSipTrace() const' '$ROOT/src/sipcore/SipEngine.cpp' && grep -q 'recentSip_.push_back(entry)' '$ROOT/src/sipcore/SipEngine.cpp' && grep -q 'recentSipTrace()' '$ROOT/src/sipcontroller.cpp'"
check "Softphone version updated" "grep -q 'Build 0.9' '$ROOT/include/trunkmonkey/Version.h'"
check "Responsive live terminal geometry" "grep -q 'TIOCGWINSZ' '$ROOT/src/terminalui.cpp' && grep -q 'resizeterm' '$ROOT/src/terminalui.cpp' && grep -q 'm_nextGeometryCheckMs' '$ROOT/src/terminalui.h'"
check "Responsive compact layout" "grep -q 'responsiveLayout' '$ROOT/src/terminalui.cpp' && grep -q 'min 24x6' '$ROOT/src/terminalui.cpp' && grep -q 'width >= 88' '$ROOT/src/terminalui.cpp'"
check "Dynamic BBS model sizing" "grep -q 'buffer->terminal->resize(cols, rows)' '$ROOT/src/terminalui.cpp' && grep -q 'terminalPaneColumns' '$ROOT/src/terminalui.cpp'"
check "Live Telnet NAWS resize" "grep -q 'CommandType::WindowSize' '$ROOT/src/telnetbackend.cpp' && grep -q 'm_nawsEnabled' '$ROOT/src/telnetbackend.cpp'"
printf '\nTermux rebuild parity gate: %d passed, %d failed\n' "$pass" "$fail"
(( fail == 0 ))
