#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
pass=0; fail=0
check(){ if eval "$2"; then printf 'PASS: %s\n' "$1"; pass=$((pass+1)); else printf 'FAIL: %s\n' "$1"; fail=$((fail+1)); fi; }
check "3.2-Termux branding" "grep -q '3.2-Termux' '$ROOT/src/appbranding.h'"
check "Dedicated Termux entry point" "test -f '$ROOT/src/main_termux.cpp' && test ! -f '$ROOT/src/main.cpp'"
check "Qt Core/Network only" "grep -q 'COMPONENTS Core Network' '$ROOT/CMakeLists.txt'"
check "No Qt Widgets" "! grep -Rqs 'Qt6::Widgets' '$ROOT/CMakeLists.txt' '$ROOT/src'"
check "No Qt Gui" "! grep -Rqs 'Qt6::Gui' '$ROOT/CMakeLists.txt' '$ROOT/src'"
check "No QApplication" "! grep -Rqs 'QApplication' '$ROOT/src'"
check "No XKB dependency" "! grep -q 'xkbcommon' '$ROOT/CMakeLists.txt'"
check "No desktop GUI source files" "test ! -e '$ROOT/src/mainwindow.cpp' && test ! -e '$ROOT/src/softphonewindow.cpp' && test ! -e '$ROOT/src/mediawindow.cpp'"
check "No CPAN command" "! grep -En '(^|[;&|[:space:]])cpan([[:space:]]|$)' '$ROOT/build-termux.sh'"
check "No Perl command" "! grep -En '(^|[;&|[:space:]])perl([[:space:]]|$)' '$ROOT/build-termux.sh'"
check "Termux pkg package manager" "grep -q 'pkg install' '$ROOT/build-termux.sh'"
check "No apt-get" "! grep -q 'apt-get' '$ROOT/build-termux.sh'"
check "Metadata-only xdg provider" "grep -q 'Contains no files' '$ROOT/build-termux.sh'"
check "Existing xdg-open reuse" "grep -q 'command -v xdg-open' '$ROOT/build-termux.sh' && grep -q 'termux-tools' '$ROOT/build-termux.sh'"
check "Explicit control permissions" "grep -q 'install -d -m 0755.*DEBIAN' '$ROOT/build-termux.sh' && grep -q 'chmod 0644.*control' '$ROOT/build-termux.sh'"
check "libopus package name" "grep -q 'libopus' '$ROOT/build-termux.sh'"
check "PJSIP 2.17 managed build" "grep -q 'branch 2.17' '$ROOT/build-termux.sh' && grep -q 'libpjproject' '$ROOT/CMakeLists.txt'"
check "PortAudio SIP backend" "grep -q -- '--with-external-pa' '$ROOT/build-termux.sh'"
check "AIM/OSCAR retained" "test -f '$ROOT/src/oscarbackend.cpp' && grep -q 'oscarbackend.cpp' '$ROOT/CMakeLists.txt'"
check "IRC retained" "test -f '$ROOT/src/ircbackend.cpp' && grep -q 'ircbackend.cpp' '$ROOT/CMakeLists.txt'"
check "IRC slash commands retained" "grep -q '/nick' '$ROOT/src/terminalui.cpp'"
check "Telnet/BBS retained" "test -f '$ROOT/src/telnetbackend.cpp' && test -f '$ROOT/src/bbsdirectory.cpp'"
check "ANSI BBS terminal retained" "test -f '$ROOT/src/ansiterminal.cpp' && grep -q 'AnsiTerminalModel' '$ROOT/src/terminalui.cpp'"
check "SIP softphone retained" "test -f '$ROOT/src/sipbackend.cpp' && test -f '$ROOT/src/sipcore/SipEngine.cpp'"
check "SIP controls retained" "grep -q '/audio-devices' '$ROOT/src/terminalui.cpp' && grep -q '/hangup' '$ROOT/src/terminalui.cpp'"
check "Secure rooms retained" "test -f '$ROOT/src/secureroom.cpp' && grep -q 'secureroom.cpp' '$ROOT/CMakeLists.txt'"
check "Encrypted transfer retained" "test -f '$ROOT/src/filetransfer.cpp' && test -f '$ROOT/src/directtransfer.cpp' && test -f '$ROOT/src/securechannel.cpp'"
check "Media/streams retained" "test -f '$ROOT/src/mediacontroller.cpp' && grep -q '/mstream' '$ROOT/src/terminalui.cpp'"
check "CLI themes retained" "grep -q 'neon-miami' '$ROOT/src/terminalui.cpp' && grep -q 'waffle-iron' '$ROOT/src/terminalui.cpp'"
check "Termux shared Downloads support" "grep -q 'storage/downloads' '$ROOT/src/terminalui.cpp'"
check "Android notification audio" "grep -q 'termux-media-player' '$ROOT/src/notificationmanager.cpp'"
check "Android browser handoff" "grep -q 'termux-open-url' '$ROOT/src/terminalui.cpp'"
check "Softphone version updated" "grep -q '3.2-Termux' '$ROOT/include/trunkmonkey/Version.h'"
printf '\nTermux rebuild parity gate: %d passed, %d failed\n' "$pass" "$fail"
(( fail == 0 ))
